name: Terraform Infra

on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: "."

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_LOG: debug

    defaults:
      run:
        working-directory: terraform

    steps:
      - uses: actions/checkout@v4

      - name: Extract branch and compute prefix
        id: branch_info
        run: |
            BRANCH=$(echo "${{ github.ref }}" | sed 's|refs/heads/||')
            FIRST_LETTER=$(echo "$BRANCH" | cut -c1 | tr '[:lower:]' '[:upper:]')
            echo "BRANCH=$BRANCH" >> $GITHUB_OUTPUT
            echo "FIRST_LETTER=$FIRST_LETTER" >> $GITHUB_OUTPUT

      - run: terraform init
      - run: terraform validate
      
      - name: Terraform Plan (Master)
        if: github.ref == 'refs/heads/master'
        run: terraform plan -var-file=tfvars/master.tfvars -var-file=tfvars/prod.tfvars
      
      - name: Terraform Plan (Non-Prod)
        if: github.ref != 'refs/heads/master'
        run: terraform plan -var-file=tfvars/master.tfvars -var-file=tfvars/nonprod.tfvars -var="branch=${{ steps.branch_info.outputs.FIRST_LETTER }}"

      - name: Apply (Master)
        if: github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve -var-file=tfvars/master.tfvars -var-file=tfvars/prod.tfvars
      
      - name: Apply (Non-Prod)
        if: github.ref != 'refs/heads/master'
        run: terraform apply -auto-approve -var-file=tfvars/master.tfvars -var-file=tfvars/nonprod.tfvars