name: Terraform Infra

on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: "."

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_LOG: debug

    defaults:
      run:
        working-directory: terraform

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - run: terraform init
      - run: terraform validate
      
      - name: Terraform Plan (Master)
        if: github.ref == 'refs/heads/master'
        run: terraform plan -var-file=tfvars/master.tfvars -var-file=tfvars/prod.tfvars
      
      - name: Terraform Plan (Non-Prod)
        if: github.ref != 'refs/heads/master'
        run: terraform plan -var-file=tfvars/master.tfvars -var-file=tfvars/nonprod.tfvars
      - name: Apply (Master)
        if: github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve -var-file=tfvars/master.tfvars -var-file=tfvars/prod.tfvars
      
      - name: Apply (Non-Prod)
        if: github.ref != 'refs/heads/master'
        run: terraform apply -auto-approve -var-file=tfvars/master.tfvars -var-file=tfvars/nonprod.tfvars