name: Terraform Infra

on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: "."
      project:
        required: true
        type: string
      branch:
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_LOG: debug

    defaults:
      run:
        working-directory: terraform

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Extract branch and compute prefix
        id: branch_info
        run: |
            BRANCH="${{ inputs.branch }}"
            if [ -z "$BRANCH" ]; then
              BRANCH="${{ github.ref_name }}"
            fi
            STACK=$(echo "$BRANCH" | cut -c1 | tr '[:lower:]' '[:upper:]')
            echo "BRANCH=$BRANCH" >> $GITHUB_OUTPUT
            echo "STACK=$STACK" >> $GITHUB_OUTPUT

      - name: Terraform init
        run: terraform init -backend-config="key=busable/${{ steps.branch_info.outputs.BRANCH }}/terraform.tfstate"
      
      - name: Terraform validate
        run: terraform validate

      - name: Terraform Plan (Prod)
        if: steps.branch_info.outputs.BRANCH == 'master'
        run: terraform plan -input=false -var-file=tfvars/master.tfvars -var-file=tfvars/prod.tfvars
      
      - name: Terraform Plan (Non-Prod)
        if: steps.branch_info.outputs.BRANCH != 'master'
        run: terraform plan -input=false -var-file=tfvars/master.tfvars -var-file=tfvars/nonprod.tfvars -var="branch=${{ steps.branch_info.outputs.STACK }}"

      - name: Apply (Prod)
        if: steps.branch_info.outputs.BRANCH == 'master'
        run: terraform apply -auto-approve -input=false -var-file=tfvars/master.tfvars -var-file=tfvars/prod.tfvars
      
      - name: Apply (Non-Prod)
        if: steps.branch_info.outputs.BRANCH != 'master'
        run: terraform apply -auto-approve -input=false -var-file=tfvars/master.tfvars -var-file=tfvars/nonprod.tfvars -var="branch=${{ steps.branch_info.outputs.STACK }}"